=== Shprrr/SappySharp/SappySharp/sappy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="sappy">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="rom"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rom">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="playlist"/>
        <xs:element minOccurs="0" ref="midimap"/>
      </xs:sequence>
      <xs:attribute name="code" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NCName">
            <xs:length value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="creator"/>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="screenshot" type="xs:NCName"/>
      <xs:attribute name="songtable" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="tagger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="song"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="steal" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="song">
    <xs:complexType mixed="true">
      <xs:attribute name="track" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="midimap">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="inst"/>
        <xs:element maxOccurs="unbounded" ref="drum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="inst">
    <xs:complexType>
      <xs:attribute name="from" use="required" type="xs:integer"/>
      <xs:attribute name="to" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="drum">
    <xs:complexType>
      <xs:attribute name="from" use="required"/>
      <xs:attribute name="kit" type="xs:integer"/>
      <xs:attribute name="to" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Shprrr/SappySharp/SappySharp/sappy.xml
<sappy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sappy.xsd">
	<rom code="KWJ6" name="Kawa's Jukebox 2006" songtable="0x3ED0" screenshot="kawajuke.jpg" creator="Kyoufu Kawa" tagger="Kyoufu Kawa">
		<playlist name="Main">
			<song track="1">Keitaro's Theme</song>
			<song track="2">Monkey Island 2</song>
			<song track="3">Toon Machine</song>
			<song track="4">Canon</song>
			<song track="5">Grabbag</song>
			<song track="6">At Doom's Gate</song>
			<song track="7">Kitchen Ace</song>
			<song track="8">I Sawed the Demons</song>
			<song track="9">Azumanga Daioh</song>
			<song track="10">Lemmings</song>
			<song track="11">Ninja Gaiden</song>
			<song track="12">Kawa's Comin'</song>
			<song track="13">Zero Wing Medley</song>
			<song track="14">Sonic Invincibility</song>
			<song track="15">Dschinghis Khan Medley</song>
		</playlist>
	</rom>
	<rom code="BDTE" name="River City Ransom" songtable="0x2C6084" screenshot="rcr.jpg" creator="Atlus" tagger="Kyoufu Kawa">
		<playlist name="Main">
			<song track="1">Introduction</song>
			<song track="2">Startup Menu</song>
			<song track="3">Running around the City</song>
			<song track="4">Playing in the Park</song>
			<song track="5">A Tough Fight</song>
			<song track="6">Save the Girl!</song>
			<song track="7">In the Factory</song>
			<song track="8">Shopping</song>
			<song track="9">A Tougher Fight</song>
			<song track="10">River City High</song>
			<song track="11">The Dragon Twins</song>
			<song track="12">Final Fight</song>
			<song track="13">Credits</song>
			<song track="14">Title Screen</song>
		</playlist>
		<playlist name="Unused">
			<song track="15">Unused</song>
			<song track="16">Unused</song>
			<song track="17">Unused</song>
		</playlist>
	</rom>
	<rom code="AW2P" name="Advance Wars 2" songtable="0x2C5638" tagger="Kyoufu Kawa">
		<playlist name="Themes">
			<song track="300">Advance Wars 2 Theme</song>
			<song track="209">Andy's Theme</song>
			<song track="217">Sami's Theme</song>
			<song track="210">Max's Theme</song>
			<song track="214">Nell's Theme</song>
			<song track="302">Hachi's Theme</song>
			<song track="213">Olaf's Theme</song>
			<song track="203">Grit's Theme</song>
			<song track="403">Colin's Theme</song>
			<song track="211">Kanbei's Theme</song>
			<song track="212">Sonja's Theme</song>
			<song track="201">Eagle's Theme</song>
			<song track="202">Drake's Theme</song>
			<song track="414">Jess's Theme</song>
			<song track="412">Flak's Theme</song>
			<song track="401">Adder's Theme</song>
			<song track="301">Lash's Theme</song>
			<song track="402">Hawke's Theme</song>
			<song track="219">Sturm's Theme</song>
			<song track="409">Black Hole Super Power!</song>
		</playlist>
	</rom>
	<rom code="A7KE" name="Kirby: Nightmare in Dream Land" songtable="0x60B460" creator="HAL">
		<playlist name="Main">
			<song track="26">Title Theme</song>
			<song track="40">Menu Screen</song>
			<song track="0">Stage Music 1</song>
			<song track="21">Stage Music 2</song>
			<song track="11">Stage Music 3</song>
			<song track="17">Stage Music 4</song>
			<song track="22">Stage Music 5</song>
			<song track="12">Stage Music 6</song>
			<song track="18">Stage Music 7</song>
			<song track="15">Stage Music 8</song>
			<song track="2">Stage Music 9</song>
			<song track="37">Metaknight Minion Battle</song>
			<song track="30">Boss Battle</song>
			<song track="1">Prelude to Victory</song>
			<song track="14">Victory</song>
			<song track="13">Long Victory</song>
			<song track="39">Arena Battle</song>
			<song track="25">Museum</song>
			<song track="38">King Dedede Battle</song>
			<song track="20">"Classic" Stage Music</song>
			<song track="27">?</song>
			<song track="31">Fountain Cinema</song>
			<song track="32">Last Stage</song>
			<song track="33">Last Boss Intro</song>
			<song track="34">Last Boss Battle</song>
			<song track="24">Ending</song>
			<song track="3">Death</song>
			<song track="4">Level 1 Background</song>
			<song track="5">Level 2 Background</song>
			<song track="6">Level 3 Background</song>
			<song track="7">Level 4 Background</song>
			<song track="8">Level 5 Background</song>
			<song track="9">Level 6 Background</song>
			<song track="10">Level 7 Background</song>
			<song track="35">Samurai Minigame</song>
			<song track="46">Bomb Minigame</song>
			<song track="42">Race Minigame</song>
			<song track="43">Race Minigame Intro</song>
			<song track="44">Race Minigame Victory</song>
			<song track="23">Lose Minigame</song>
			<song track="28">Win Minigame</song>
			<song track="29">First Prize in Minigame</song>
			<song track="19">Invincible</song>
			<song track="16">Game Over</song>
			<song track="47">Stage Music no intro 1</song>
			<song track="53">Stage Music no intro 2</song>
			<song track="48">Stage Music no intro 3</song>
			<song track="50">Stage Music no intro 4</song>
			<song track="54">Stage Music no intro 5</song>
			<song track="49">Stage Music no intro 6</song>
			<song track="51">Stage Music no intro 7</song>
			<song track="55">Stage Music no intro 8</song>
			<song track="52">Classic Stage no intro</song>
		</playlist>
	</rom>
	<rom code="AXVE" name="Pokémon Ruby" songtable="0x45548C" creator="Gamefreak">
		<playlist name="Main">
			<song track="0x19E">Introduction</song>
			<song track="0x1BA">The Pokémon!</song>
			<song track="0x19D">Title Screen</song>
			<song track="0x195">Littleroot Town</song>
			<song track="0x16B">Oldale Town</song>
			<song track="0x16A">Petalburg City</song>
			<song track="0x18F">Rustboro City</song>
			<song track="0x1AB">Dewford Town</song>
			<song track="0x1B1">Slateport City</song>
			<song track="0x18E">Verdanturf Town</song>
			<song track="0x1B5">Lavaridge Town</song>
			<song track="0x17E">Fortree City</song>
			<song track="0x198">Lilycove City</song>
			<song track="0x1BD">Sootopolis City</song>
			<song track="0x1A6">Evergrande City</song>
			<song track="0x167">Route Theme 1</song>
			<song track="0x168">Route Theme 2</song>
			<song track="0x169">Route Theme 3</song>
			<song track="0x176">Route Theme 4</song>
			<song track="0x191">Route Theme 5</song>
			<song track="0x192">Route Theme 6</song>
			<song track="0x1A2">Route Theme 7</song>
			<song track="0x199">The Sandy Desert</song>
			<song track="0x16E">Caves and Darkness</song>
			<song track="0x17D">A Far-away Place</song>
			<song track="0x1A9">Riding the Cable Car</song>
			<song track="0x182">Meteor Falls</song>
			<song track="0x1B2">The Fog of Mt. Pyre</song>
			<song track="0x1B0">Shoal Cave</song>
			<song track="0x1AD">Victory Road</song>
			<song track="0x1B6">Island Cave</song>
			<song track="0x196">Sky Pillar</song>
			<song track="0x16D">Surfing</song>
			<song track="0x193">Bicycle Ride</song>
			<song track="0x19B">Underwater Dive</song>
			<song track="0x1AF">Sailing the Sea</song>
			<song track="0x1BB">The Flood</song>
			<song track="0x1BC">Unknown Place</song>
			<song track="0x190">Pokémon Center</song>
			<song track="0x194">PokeMart</song>
			<song track="0x16C">Gym</song>
			<song track="0x1AE">Team Hideout</song>
			<song track="0x1C0">You're Being Watched!</song>
			<song track="0x1C4">Beauty Contest Lobby</song>
			<song track="0x175">Lilycove Museum</song>
			<song track="0x177">Slateport Museum</song>
			<song track="0x1B3">Pokémon Trainer School</song>
			<song track="0x17F">Birch's Lab</song>
			<song track="0x1AA">Game Corner</song>
			<song track="0x180">Battle Tower</song>
			<song track="0x1AC">Safari Zone</song>
			<song track="0x1B8">Beauty Contest</song>
			<song track="0x1BE">Berry Blending Results</song>
			<song track="0x1A4">Show Me Around</song>
			<song track="0x17C">Boy Encounter</song>
			<song track="0x197">Girl Encounter</song>
			<song track="0x1C1">Kid Encounter</song>
			<song track="0x17B">Tuber Encounter</song>
			<song track="0x181">Swimmer Encounter</song>
			<song track="0x18D">Ship Encounter</song>
			<song track="0x1C3">Sailor Encounter</song>
			<song track="0x1A0">Electric Encounter</song>
			<song track="0x1A1">Biker Encounter</song>
			<song track="0x1A3">Aqua Encounter</song>
			<song track="0x1B9">Magma Encounter</song>
			<song track="0x1A7">Psychic Encounter</song>
			<song track="0x1C6">Unknown Encounter</song>
			<song track="0x1C2">Elite Four Theme</song>
			<song track="0x19F">May's Theme</song>
			<song track="0x1A5">Brendan's Theme</song>
			<song track="0x1C5">What's On TV?</song>
			<song track="0x19A">Help Me!</song>
			<song track="0x188">Unknown Theme 1</song>
			<song track="0x1C9">Battle - Wild Pokémon</song>
			<song track="0x1D0">Battle - Rival</song>
			<song track="0x1CB">Battle - Pokémon Trainer</song>
			<song track="0x1CC">Battle - Gym Leader</song>
			<song track="0x1CA">Battle - Aqua/Magma</song>
			<song track="0x1D2">Battle - Team Leader</song>
			<song track="0x1D1">Battle - Elite Four</song>
			<song track="0x1CD">Battle - Champion Steven</song>
			<song track="0x1CE">Battle - Regirock, Regice and Registeel</song>
			<song track="0x1CF">Battle - Legendary Pokémon</song>
			<song track="0x161">Wild Pokémon Defeat w/Intro</song>
			<song track="0x160">Wild Pokémon Defeat</song>
			<song track="0x19C">Trainer Defeat</song>
			<song track="0x162">Gym Leader Defeat</song>
			<song track="0x1A8">Important Defeat</song>
			<song track="0x1B7">Important 2 Defeat</song>
			<song track="0x163">Acquired Badge</song>
			<song track="0x16F">Level Up</song>
			<song track="0x170">Pokémon Healed</song>
			<song track="0x171">Big Victory</song>
			<song track="0x172">Acquired Item</song>
			<song track="0x173">Pokémon Caught</song>
			<song track="0x174">Got TM/HM</song>
			<song track="0x183">Got a Berry</song>
			<song track="0x178">Evolve Intro</song>
			<song track="0x179">Evolving</song>
			<song track="0x184">Unknown Victory 1</song>
			<song track="0x185">Unknown Victory 2</song>
			<song track="0x186">Unknown Victory 3</song>
